# Generated by Django 3.2.9 on 2021-11-10 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0004_auto_20211110_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(max_length=2000)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='chat_backend.user')),
            ],
        ),
    ]
